const {test}=require('node:test');
const assert=require('node:assert/strict');
const E=require('../js/configurator-engine.js');
const cat=require('./catalog-fixture.cjs');
const apply=(s,state)=>E.apply(s,cat,state);
const count=(state,id)=>state.elements.filter(e=>e.assetId===id).length;
const A='Crea un acchiappasogni per la nascita di Sofia con un cerchio da 30 cm, due cerchi da 10 cm sotto, intreccio rosa e bianco, quattro piume rosa, due piume bianche, perline di legno e una luna. Scrivi Sofia al centro.';
test('A: quantities, sizes, colors, material, theme, text and layout',()=>{
 const r=apply(A),s=r.state;
 assert.equal(count(s,'r30'),1);assert.equal(count(s,'r10'),2);assert.equal(count(s,'pink'),4);assert.equal(count(s,'white'),2);assert.equal(count(s,'wood'),1);assert.equal(count(s,'moon'),1);
 assert.deepEqual(s.themes,['nascita']);assert.equal(s.text,'Sofia');assert.deepEqual(s.weaveColors,['rosa','bianco']);
 const large=s.elements.find(e=>e.assetId==='r30'),small=s.elements.filter(e=>e.assetId==='r10');assert.ok(small.every(e=>e.y>large.y&&e.size<large.size));assert.notEqual(small[0].x,small[1].x);assert.equal(r.total,26.7);assert.deepEqual(r.warnings,[]);
});
test('B: wedding, sizes, side positions and real flowers',()=>{const {state:s}=apply('Vorrei un acchiappasogni per matrimonio con un cerchio da 37 cm, due cerchi da 14 cm ai lati, colori bianco e beige, piume bianche e decorazioni floreali.');assert.equal(count(s,'r37'),1);assert.equal(count(s,'r14'),2);assert.equal(count(s,'white'),1);assert.equal(count(s,'flower'),1);assert.deepEqual(s.themes,['matrimonio']);assert.deepEqual(s.colors,['bianco','beige']);const sides=s.elements.filter(e=>e.assetId==='r14');assert.ok(sides[0].x<500&&sides[1].x>500);});
test('Multiple sizes including written and numeric quantities',()=>{const s=apply('un cerchio da 30 cm, due cerchi da 10 cm e un cerchio da 6 cm').state;assert.equal(count(s,'r30'),1);assert.equal(count(s,'r10'),2);assert.equal(count(s,'r6'),1);assert.equal(apply('3 cerchi da 6 cm').state.elements.length,3);});
test('Modification preserves rings and changes exact quantities',()=>{const s=apply(A).state,r=apply('togli due piume rosa e aggiungi una piuma bianca',s);assert.equal(count(r.state,'pink'),2);assert.equal(count(r.state,'white'),3);assert.equal(count(r.state,'r30'),1);assert.equal(count(r.state,'r10'),2);});
test('Pronoun memory',()=>{let s=apply('quattro piume rosa').state;s=apply('togliene due',s).state;assert.equal(count(s,'pink'),2);});
test('Unavailable asset never invented',()=>{const r=apply('aggiungi una conchiglia');assert.equal(r.state.elements.length,0);assert.match(r.warnings.join(' '),/non è attualmente disponibile/);});
test('Dynamic shell type with metadata, without type-specific code',()=>{const custom={id:'shell1',name:'Conchiglia bianca',type:'shell',image:'assets/icon-192-1.png',keywords:['conchiglia','mare'],metadata:{color:'bianco'},price_modifier:1};const r=E.apply('aggiungi una conchiglia', [...cat,custom]);assert.equal(count(r.state,'shell1'),1);assert.equal(r.total,1);});
test('Prices 30 cm + two 10 cm = 23 EUR',()=>{assert.equal(apply('un cerchio da 30 cm, due cerchi da 10 cm').total,23);});
test('Null, JSON and incomplete metadata; invalid prices',()=>{for(const metadata of [null,'bad JSON','{"keywords":["test"]}',{},[]])assert.doesNotThrow(()=>E.catalog([{id:'x',name:'X',type:'unknown',metadata}]));for(const value of [null,undefined,'bad',NaN,Infinity,-1])assert.equal(E.money(value),0);assert.equal(E.money('1,50'),1.5);assert.equal(E.money(0),0);});
test('Inactive and wrong material/color not selected',()=>{const c=cat.map(a=>({...a,active:false}));assert.equal(E.apply('una luna',c).state.elements.length,0);assert.equal(apply('perline di metallo').state.elements.length,0);assert.equal(apply('una piuma verde').state.elements.length,0);});
test('Ambiguous diameter asks deterministic clarification',()=>{const r=apply('metti due cerchi piccoli');assert.equal(r.state.elements.length,0);assert.match(r.warnings.join(' '),/misura/);});
test('Move small ring and global movement preserve size',()=>{let s=apply('un cerchio da 30 cm, un cerchio da 10 cm sotto').state;s=apply('sposta il cerchio piccolo a destra',s).state;assert.ok(s.elements.find(e=>e.assetId==='r10').x>700);const y=s.elements[0].y;s=apply('sposta tutto più in basso',s).state;assert.equal(s.elements[0].y,y+60);});
test('Recolor substitutes only an available variant and updates price',()=>{let s=apply('quattro piume rosa e due piume bianche').state;s=apply('cambia le piume rosa in bianche',s).state;assert.equal(count(s,'white'),6);assert.equal(count(s,'pink'),0);assert.equal(E.price(s,cat),3);});
test('Elliptical white feathers after pink feathers',()=>{const s=apply('quattro piume rosa e due bianche').state;assert.equal(count(s,'pink'),4);assert.equal(count(s,'white'),2);});
test('Quantities and alignment on current composition',()=>{let s=apply('due piume rosa').state;s=apply('porta le piume rosa a quattro',s).state;assert.equal(count(s,'pink'),4);s=apply('allinea le piume rosa al centro',s).state;assert.ok(s.elements.every(e=>e.position==='center'));});
test('Limits protect browser and project bounds',()=>{const r=apply('aggiungi 999999 piume rosa');assert.equal(r.state.elements.length,100);assert.ok(r.warnings.length);let s=r.state;for(let i=0;i<3;i++)s=apply('aggiungi 999999 piume rosa',s).state;assert.equal(s.elements.length,250);assert.ok(s.elements.every(e=>e.x>=0&&e.x<=1000&&e.y>=0&&e.y<=1200));});
test('Diameter scale preserves 70 versus 20 proportions',()=>{const s=apply('un cerchio da 70 cm, un cerchio da 20 cm sotto').state;assert.ok(Math.abs(s.elements[0].size/s.elements[1].size-3.5)<1e-10);});
test('Text dedication and meaning retained',()=>{const s=apply('dedica: Per la nostra piccola stella. Significato famiglia.').state;assert.equal(s.text,'Per la nostra piccola stella');assert.deepEqual(s.meanings,['famiglia']);});
test('Atomic bundled extra charged once per bundle',()=>{const bundle={id:'bundle',name:'Confetti bigliettino bustina',type:'extra',price_modifier:0.4,keywords:['confezione'],metadata:{keywords:['confetti + bigliettino + bustina']}};const r=E.apply('una confezione',[...cat,bundle]);assert.equal(count(r.state,'bundle'),1);assert.equal(r.total,0.4);});
test('Compatibility blocks unsupported additions',()=>{const c=[...cat,{id:'a',name:'Decorazione',type:'custom',metadata:{incompatibility:['ring']}}];const s=E.apply('un cerchio da 30 cm',c).state;assert.equal(E.apply('aggiungi una decorazione',c,s).state.elements.length,1);});

test('Bounded layout avoids overlapping many rings',()=>{const s=apply('vingt').state;assert.equal(s.elements.length,0);const r=apply('aggiungi venti cerchi da 30 cm sotto').state;for(let i=0;i<r.elements.length;i++)for(let j=i+1;j<r.elements.length;j++){const a=r.elements[i],b=r.elements[j];assert.ok(Math.hypot(a.x-b.x,a.y-b.y)>=(a.size+b.size)/2);}});
test('Text is not interpreted as an accessory request',()=>{const r=apply('dedica: Per la nostra piccola stella.');assert.equal(r.state.elements.length,0);assert.deepEqual(r.warnings,[]);});
test('Distinct ring, weave and feather colors are preserved',()=>{const whiteRings=cat.map(a=>a.type==='ring'?{...a,metadata:{...a.metadata,color:'bianco'}}:a);const r=E.apply('un cerchio da 30 cm, cerchio bianco, intreccio rosa e bianco, due piume rosa',whiteRings);assert.equal(r.state.elements[0].assetId,'r30');assert.deepEqual(r.state.weaveColors,['rosa','bianco']);assert.equal(count(r.state,'pink'),2);assert.deepEqual(r.warnings,[]);});

test('Move current dedication keeps text and remembers initial idea',()=>{let s=apply('Scrivi Sofia al centro.').state;s=apply('metti Sofia più in alto',s).state;assert.equal(s.text,'Sofia');assert.equal(s.textY,130);assert.equal(s.initialIdea,'Scrivi Sofia al centro.');assert.equal(s.history.length,2);});

test('Bundle components across clauses are billed only once',()=>{const bundle={id:'bundle',name:'Confezione',type:'extra',price_modifier:.4,metadata:{bundle_components:['confetti','bigliettino','bustina']}};const r=E.apply('confetti, bigliettino e bustina',[bundle]);assert.equal(r.state.elements.length,1);assert.equal(r.total,.4);assert.equal(E.apply('un bigliettino',[bundle]).state.elements.length,0);});

test('Singular named variant replacement respects explicit quantity',()=>{const s=apply('quattro piume rosa').state;const r=apply('cambia una piuma rosa in bianca',s);assert.equal(count(r.state,'pink'),3);assert.equal(count(r.state,'white'),1);assert.deepEqual(r.warnings,[]);});
test('Explicit RECOLOR intent uses a real variant',()=>{const s=apply('quattro piume rosa').state;const r=apply('colora le piume di bianco',s);assert.equal(r.parsed.requests[0].intent,'RECOLOR');assert.equal(count(r.state,'white'),4);});

test('Quantities bind to the closest noun after introductory un',()=>{const r=apply('crea un acchiappasogni con 4 piume rosa');assert.equal(count(r.state,'pink'),4);const r2=apply('vorrei un acchiappasogni con due cerchi da 10 cm');assert.equal(count(r2.state,'r10'),2);});
