// Eseguire con Playwright disponibile; nessuna richiesta a servizi reali.
import { createRequire } from 'node:module'
const require=createRequire(import.meta.url)
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']})
const assets=[30,10,6].map(n=>({id:'f'+n,name:`Cerchio ${n} cm`,type:'frame',image:'/favicon.svg',price_modifier:4,active:true})).concat([{id:'pink',name:'Piuma rosa',type:'feather',image:'/favicon.svg',price_modifier:.5,active:true},{id:'white',name:'Piuma bianca',type:'feather',image:'/favicon.svg',price_modifier:.5,active:true}])
const mock=`const tables={configurator_assets:${JSON.stringify(assets)},categories:[{id:'c',name:'Classici',slug:'classici',active:true}],products:[{id:'p',name:'Prodotto prova',price:10,category_name:'Classici',active:true,stock:5,images:[]} ]};window.__testTables=tables;export const supabase={from(t){let op=null,payload=null;const q={select(){return q},eq(){return q},order(){return q},limit(){return q},single(){return Promise.resolve({data:tables[t]?.[0]||null,error:null})},maybeSingle(){return q.single()},insert(p){op='insert';payload=p;return q},update(p){op='update';payload=p;return q},delete(){return q},then(ok){if(op==='insert'){tables[t]??=[];tables[t].push({...payload,id:'test-'+tables[t].length})}if(op==='update'&&tables[t]?.length)Object.assign(tables[t].at(-1),payload);return Promise.resolve({data:[...(tables[t]||[])],error:null}).then(ok)}};return q},auth:{getUser:async()=>({data:{user:{id:'fixture',email:'fixture',user_metadata:{}}},error:null}),getSession:async()=>({data:{session:null}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})},rpc:async()=>({data:true,error:null}),storage:{from:()=>({upload:async()=>({error:null}),getPublicUrl:()=>({data:{publicUrl:'/favicon.svg'}})})},functions:{invoke:async()=>({data:null,error:null})}};`
const routes=['/','/shop','/shop?q=prova','/prodotto/p','/carrello','/checkout','/personalizzati','/configuratore','/admin','/admin/configuratore','/admin/categorie','/admin/ordini']
let failures=[]
for(const width of [360,390,1280]){
 const page=await browser.newPage({viewport:{width,height:900}});let errors=[]
 page.on('pageerror',e=>errors.push(e.message))
 await page.route('**/src/supabaseClient.js',r=>r.fulfill({contentType:'application/javascript',body:mock}))
 for(const path of routes){await page.goto('http://127.0.0.1:5173'+path);await page.waitForTimeout(180);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);if(errors.length||overflow)failures.push({width,path,errors:[...errors],overflow});errors=[]}
 await page.goto('http://127.0.0.1:5173/configuratore');await page.locator('.dc-idea textarea').fill('un cerchio da 30 cm, due cerchi da 10 cm sotto, quattro piume rosa');await page.getByRole('button',{name:'Crea la bozza'}).click();await page.locator('#dc-command').fill('togli due piume rosa e aggiungi una piuma bianca');await page.getByRole('button',{name:'Applica modifica'}).click();const count=await page.locator('.dc-canvas image').count();if(count!==6)failures.push({width,count});await page.getByPlaceholder('Nome e cognome').fill('Cliente test');await page.getByPlaceholder('Email',{exact:true}).fill('cliente@example.test');await page.getByRole('button',{name:'Invia richiesta',exact:true}).click();await page.getByText('Richiesta inviata a Erika con la foto del progetto!',{exact:true}).waitFor();await page.getByRole('button',{name:'Inviato',exact:true}).click();if(await page.evaluate(()=>window.__testTables.custom_projects.length)!==1)failures.push({width,duplicateProject:true});await page.screenshot({path:`/tmp/ery-${width}.png`,fullPage:true});
 await page.goto('http://127.0.0.1:5173/admin/configuratore');
 await page.locator('#name').fill('Conchiglia test');await page.locator('#type').fill('shell');await page.getByText('Metadati opzionali per riconoscere la tua idea').click();await page.locator('#meta-keywords').fill('conchiglia, mare');await page.locator('#meta-color').fill('bianco');await page.getByRole('button',{name:'Salva elemento',exact:true}).click();
 await page.waitForTimeout(150);
 const card=page.locator('article.asset-card').filter({hasText:'Conchiglia test'});await card.getByRole('button',{name:'Modifica',exact:true}).click();if(await page.locator('#meta-keywords').inputValue()!=='conchiglia, mare')failures.push({width,metadata:'lost'});await page.locator('#meta-material').fill('conchiglia');await page.getByRole('button',{name:'Salva modifiche',exact:true}).click();await card.getByRole('button',{name:'Disattiva',exact:true}).click();await page.waitForTimeout(100);if(!await card.locator('.status-badge').getByText('Disattivato').count())failures.push({width,active:'failed'});
 await page.close()
}
await browser.close();console.log(JSON.stringify({routes:routes.length,widths:[360,390,1280],failures},null,2));if(failures.length)process.exitCode=1
